{{- range $_, $service := .Values.externalIngressroute }}
{{- if has "compress" $service.middlewares }}
# Enable gzip compression
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "application-chart-template.external-service-name" (dict "root" $ "service" $service ) }}-compress
spec:
  compress: {}
{{- end }}
{{- end }}
